### ISSUE TITLE
sharing the model and the metric

### ISSUE THREAD

**Issue by tianlu-wang** [kelichiu/GPT3-hate-speech-detection#3]
Hi there,

Thanks for releasing the prompt data. Would you mind also sharing the model you used and the code on how to measure if a prediction is correct or not? Really appreciate that!!

**Comment by RohanAlexander** [comment]
Hi Tianlu,

Not sure if I'm misunderstanding what you're asking for, but the model is GPT-3.
Whether a prediction is correct or not is a count so there's not really anything fancy to the code for that and it is in paper.Rmd.

Rohan
